const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');
const dotenv = require('dotenv');
const express = require('express');
const mysql = require('mysql');



dotenv.config();

const StaffRegisterController = (app, db) => {
  // Helper function to run SQL queries using db.promise().query
  const query = async (sql, params) => {
    try {
      const [results, fields] = await db.promise().query(sql, params);
      return results;
    } catch (error) {
      throw error;
    }
  };

  app.post("/reg/stf", async (req, res) => {
    try {
      const {
        stfName,
        stfEmail,
        stfPhone,
        stfAddress,
        stfUserName,
        stfPassword,
        stfStaffType
      } = req.body;

      // Check if staff username already exists
      const existingStaff = await query('SELECT * FROM stf_login WHERE userName = ?', [stfUserName]);

      if (existingStaff.length > 0) {
        return res.status(400).send({ message: "Staff username already exists" });
      }

      // Hash the staff password
      const hashedPassword = await bcrypt.hash(stfPassword, 10);

      // Start a transaction
      const connection = await db.promise();
      try {
        // Insert staff details
        const [staffDetailsResult] = await connection.query(
          'INSERT INTO stf_details (stfName, stfMail, stfPhone, stfAddress, stfStaffType) VALUES (?, ?, ?, ?, ?)',
          [stfName, stfEmail, stfPhone, stfAddress, stfStaffType]
        );

        // Retrieve the staff ID generated by the database
        const staffId = staffDetailsResult.insertId;

        // Insert staff login details
        await connection.query(
          'INSERT INTO stf_login (stf_id, userName, password) VALUES (?, ?, ?)',
          [staffId, stfUserName, hashedPassword]
        );

        // Commit the transaction
        await connection.commit();

        // Registration successful
        console.log("Staff Registered Successfully");
        res.status(201).send({ message: "STAFF REGISTRATION SUCCESSFUL!" });
      } catch (err) {
        // Rollback the transaction in case of an error
        await connection.rollback();
        throw err;
      } finally {
        // Release the connection
        connection.close();
      }
    } catch (error) {
      console.error("Error during staff registration:", error);
      res.status(500).send({ error: "Internal Server Error" });
    }
  });

}


module.exports = StaffRegisterController;
